WEB/Models/Entities/ClientDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB.Models.Entities
{
    public class ClientDetail
    {
        public Guid Id { get; set; }

        [ForeignKey("ServiceDescription")]
        public Guid? ServiceDescriptionId { get; set; }
        public virtual ServiceDescription ServiceDescription { get; set; }


        [ForeignKey("ServiceCode")]
        [Required]
        public int? ServiceCodeId { get; set; }
        public virtual ServiceCode ServiceCode { get; set; }

        [Required]
        [Display(Name = "Шаблон XML из SoapUI")]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public string RequestXML { get; set; }
    }
}

WEB/Models/Entities/ServiceDescription.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WEB.Models.Enums;

namespace WEB.Models.Entities
{
    public class ServiceDescription
    {
        public Guid Id { get; set; }
        [Display(Name = "Имя соединения(сервиса/клиента)")]
        [Required]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Номер действующего соглашения")]
        public string AgreementNo { get; set; }

        [Required]
        [Display(Name = "Тип соединения")]
        public ConnectionType ConnectionType { get; set; }

        [Required]
        [Display(Name = "Вид взаимодействия")]
        public InteractionType InteractionType { get; set; }

        [Display(Name = "Статус (активный/неактивный)")]
        public bool IsActive { get; set; }

        public virtual ICollection<ClientDetail> ClientDetails { get; set; }
        public virtual ICollection<ServiceDetail> ServiceDetails { get; set; }
    }
}

WEB/Models/Entities/ServiceDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WEB.Models.Entities
{
    public class ServiceDetail
    {
        public int Id { get; set; }
        [ForeignKey("ServiceDescription")]
        public Guid? ServiceDescriptionId { get; set; }
        public virtual ServiceDescription ServiceDescription { get; set; }


        [ForeignKey("ServiceCode")]
        [Required]
        public int? ServiceCodeId { get; set; }
        public virtual ServiceCode ServiceCode { get; set; }
    }
}

WEB/Controllers/ServiceBuilderController.cs
using ClassLibrary;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB.Controllers
{
    [Authorize]
    public class ServiceBuilderController : Controller
    {
        public ActionResult CreateProjectFolder(string name, bool isTunduk = false)
        {
            if (!isTunduk)
                return Json(new { result = CMD_Commands.CreateProjectFolder(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
            else
            {
                return Json(new { result = CMD_Commands.CreateWCFProjectFolder(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult PublishToPackage(string name, bool withDeploy = false)
        {
            if (!withDeploy)
            {
                return Json(new { result = CMD_Commands.PublishToPackage(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { result = CMD_Commands.PublishToPackage(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult IsPublished(string name)
        {
            return Json(new { result = CMD_Commands.IsPublished(name) }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult CheckDeploy(string name)
        {
            return Json(new { result = CMD_Commands.DeployWCF(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Deploy(string name)
        {
            return Json(new { result = CMD_Commands.DeployWCF(name, out List<string> outputLines, out string error, true), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult IsDeployed(string name)
        {
            var isDeployed = CMD_Commands.IsDeployed(name);
            if (isDeployed)
            {
                return Json(new { result = true, serviceUrl = "http://localhost/Tunduk" + name + "/Service.svc" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { result = false }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult CheckProjectFolder(string name)
        {
            return Json(new { result = CMD_Commands.ExistFolder(name, false) }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult HasBuilding(string name)
        {
            var prjPath = CMD_Commands.GetFullProjectPath(name);
            prjPath = CMD_Commands.GetFullProjectPath(prjPath, "bin\\service.exe");
            return Json(new { result = CMD_Commands.HasFile(prjPath) }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult BuildProject(string name)
        {
            return Json(new { result = CMD_Commands.BuildProject(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult RebuildProject(string name)
        {
            return Json(new { result = CMD_Commands.RebuildProject(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult InstallService(string name)
        {
            return Json(new { result = CMD_Commands.InstallService(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UninstallService(string name)
        {
            return Json(new { result = CMD_Commands.UninstallService(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult StartService(string name)
        {
            return Json(new { result = CMD_Commands.StartService(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult StopService(string name)
        {
            return Json(new { result = CMD_Commands.StopService(name, out List<string> outputLines, out string error), error, outputLines = outputLines.ToArray() }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetWinServiceInfo(string name)
        {
            CMD_Commands.GetWinServiceInfo(name, out bool isExist, out bool isStarted, out string error);
            return Json(new { result = string.IsNullOrEmpty(error), isExist, isStarted, error }, JsonRequestBehavior.AllowGet);
        }
    }
}

WEB/Controllers/ServiceDescriptionsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEB.Models;
using WEB.Models.Entities;

namespace WEB.Controllers
{
    [Authorize]
    public class ServiceDescriptionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ServiceDescriptionsController()
        {
            ViewBag.ServiceDescriptionsNav = "active";
        }
        public ActionResult Index()
        {
            return View(db.ServiceDescriptions.ToList());
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceDescription serviceDescription = db.ServiceDescriptions.Find(id);
            if (serviceDescription == null)
            {
                return HttpNotFound();
            }
            return View(serviceDescription);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,AgreementNo,ConnectionType,InteractionType,IsActive")] ServiceDescription serviceDescription)
        {
            if (db.ServiceDescriptions.Any(x => x.Name.Trim().ToUpper() == serviceDescription.Name.Trim().ToUpper()))
                ModelState.AddModelError("Name", "Сервис с таким именем уже существует в базе-данных");
            if (ModelState.IsValid)
            {
                serviceDescription.Id = Guid.NewGuid();
                serviceDescription.Name = serviceDescription.Name.Trim().ToUpper();
                db.ServiceDescriptions.Add(serviceDescription);
                db.SaveChanges();
                return RedirectToAction("Details", new { serviceDescription.Id });
            }

            return View(serviceDescription);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceDescription serviceDescription = db.ServiceDescriptions.Find(id);
            if (serviceDescription == null)
            {
                return HttpNotFound();
            }
            return View(serviceDescription);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,AgreementNo,ConnectionType,InteractionType,IsActive")] ServiceDescription serviceDescription)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceDescription).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { serviceDescription.Id });
            }
            return View(serviceDescription);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceDescription serviceDescription = db.ServiceDescriptions.Find(id);
            if (serviceDescription == null)
            {
                return HttpNotFound();
            }
            return View(serviceDescription);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ServiceDescription serviceDescription = db.ServiceDescriptions.Find(id);
            db.ServiceDescriptions.Remove(serviceDescription);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SelectTundukOrganization(Guid serviceId, int? id, string returnAction)
        {
            ViewBag.serviceId = serviceId;
            ViewBag.returnAction = returnAction;
            if (id != null)
            {
                return RedirectToAction("SelectSubsystem", new { serviceId, tundukOrganizationId = id, returnAction });
            }
            return View(db.TundukOrganizations.ToList());
        }

        public ActionResult SelectSubsystem(Guid serviceId, int tundukOrganizationId, int? id, string returnAction)
        {
            ViewBag.serviceId = serviceId;
            ViewBag.returnAction = returnAction;
            ViewBag.OrganizationName = db.TundukOrganizations.Find(tundukOrganizationId).Name;
            if (id != null)
            {
                return RedirectToAction(returnAction, new { serviceId, subsystemId = id });
            }
            var subsystems = db.Subsystems.Where(x => x.TundukOrganizationId == tundukOrganizationId).ToList();
            if(subsystems.Count == 1)
            {
                return RedirectToAction(returnAction, new { serviceId, subsystemId = subsystems[0].Id });
            }
            return View(subsystems);
        }

        public ActionResult CreateClientDetails(Guid serviceId, int? subsystemId)
        {
            if(subsystemId == null)
            {
                return RedirectToAction("SelectTundukOrganization", new { serviceId, returnAction = "CreateClientDetails" });
            }

            var serviceCodes = db.ServiceCodes.Where(x => x.SubsystemId == subsystemId).ToList();
            ViewBag.ServiceCodeId = (from sc in serviceCodes
                                     select new SelectListItem
                                     {
                                         Text = sc.Name,
                                         Value = sc.Id.ToString()
                                     });
            ViewBag.SubsystemId = subsystemId;
            var subsystem = db.Subsystems.Find(subsystemId);
            ViewBag.OrganizationName = db.TundukOrganizations.Find(subsystem.TundukOrganizationId).Name;
            ViewBag.SubsystemName = subsystem.Name;
            return View(new ClientDetail { ServiceDescriptionId = serviceId });
        }
        [HttpPost]
        public ActionResult CreateClientDetails(ClientDetail obj, int? subsystemId)
        {
            var objDb = db.ClientDetails.FirstOrDefault(x => x.ServiceCodeId == obj.ServiceCodeId);
            if (objDb != null)
            {
                ModelState.AddModelError("ServiceCodeId", "Для указанного сервиса клиент уже существует! Name: " + objDb.ServiceDescription.Name);
            }
            if (ModelState.IsValid)
            {
                obj.Id = Guid.NewGuid();
                db.ClientDetails.Add(obj);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = obj.ServiceDescriptionId });
            }

            ViewBag.ServiceCodeId = (from sc in db.ServiceCodes
                                     where sc.SubsystemId == subsystemId
                                     select new SelectListItem
                                     {
                                         Text = sc.Name,
                                         Value = sc.Id.ToString(),
                                         Selected = sc.Id == obj.ServiceCodeId
                                     }).ToList();
            ViewBag.SubsystemId = subsystemId;
            var subsystem = db.Subsystems.Find(subsystemId);
            ViewBag.OrganizationName = db.TundukOrganizations.Find(subsystem.TundukOrganizationId).Name;
            ViewBag.SubsystemName = subsystem.Name;
            return View(obj);
        }

        public ActionResult ClientDetails(Guid detailsId)
        {
            return PartialView(db.ClientDetails.Find(detailsId));
        }

        public ActionResult CreateServiceDetails(Guid serviceId, int? subsystemId)
        {
            if (subsystemId == null)
            {
                var ownerTundukMemberCode = ConfigurationManager.AppSettings["c_memberCode"];
                if (!string.IsNullOrEmpty(ownerTundukMemberCode))
                {
                    var orgFromDb = db.TundukOrganizations.FirstOrDefault(x => x.MemberCode == ownerTundukMemberCode);
                    if(orgFromDb != null)
                    {
                        return RedirectToAction("SelectTundukOrganization", new { orgFromDb.Id, serviceId, returnAction = "CreateServiceDetails" });
                    }
                }
                return RedirectToAction("SelectTundukOrganization", new { serviceId, returnAction = "CreateServiceDetails" });
            }

            var serviceCodes = db.ServiceCodes.Where(x => x.SubsystemId == subsystemId).ToList();
            ViewBag.ServiceCodeId = (from sc in serviceCodes
                                     select new SelectListItem
                                     {
                                         Text = sc.Name,
                                         Value = sc.Id.ToString()
                                     });
            ViewBag.SubsystemId = subsystemId;
            var subsystem = db.Subsystems.Find(subsystemId);
            ViewBag.OrganizationName = db.TundukOrganizations.Find(subsystem.TundukOrganizationId).Name;
            ViewBag.SubsystemName = subsystem.Name;
            var serviceDesc = db.ServiceDescriptions.Find(serviceId);
            return View(new ServiceDetail { ServiceDescriptionId = serviceId });
        }
        [HttpPost]
        public ActionResult CreateServiceDetails(ServiceDetail obj, int? subsystemId)
        {
            var objDb = db.ServiceDetails.FirstOrDefault(x => x.ServiceCodeId == obj.ServiceCodeId);
            if (objDb != null)
                ModelState.AddModelError("ServiceCodeId", "Адаптер с таким ServiceCode уже зарегистрирован! Name: " + objDb.ServiceDescription.Name);
            if (ModelState.IsValid)
            {
                db.ServiceDetails.Add(obj);
                db.SaveChanges();

WEB/Views/ServiceDescriptions/ClientDetails.cshtml
@model WEB.Models.Entities.ClientDetail
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.ServiceCode.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ServiceCode.Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.ServiceCode.WsdlPath)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ServiceCode.WsdlPath)
    </dd>
</dl>

WEB/Views/ServiceDescriptions/Create.cshtml
@model WEB.Models.Entities.ServiceDescription

@{
    ViewBag.Title = "Создать соединение";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgreementNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgreementNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgreementNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConnectionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ConnectionType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ConnectionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InteractionType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.InteractionType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InteractionType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@section breadcrumb{
    <li class="breadcrumb-item">@Html.ActionLink("Список сервисов", "Index")</li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
}

WEB/Views/ServiceDescriptions/ServiceDetails.cshtml
@model WEB.Models.Entities.ServiceDetail
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.ServiceCode.Name)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ServiceCode.Name)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.ServiceCode.WsdlPath)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ServiceCode.WsdlPath)
    </dd>
</dl>

WEB/Views/ServiceDescriptions/_LineChart.cshtml
<div class="card">
    <div class="card-header">
        <i class="fas fa-chart-area"></i> @ViewBag.Name: @ViewBag.ConnectionType activities
    </div>
    <div class="card-body">
        @*<h5 class="card-title">Title</h5>
        <p class="card-text">Text...</p>*@
        <div id="line_chart"></div>
    </div>
</div>

WEB/Views/ServiceDescriptions/_TundukClientOperations.cshtml
@model WEB.Models.Entities.ServiceDescription
<div class="row">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Заполните параметры запроса:</h5>
                <p class="card-text inputParams text-center soapRequest"><img width="150" height="150" src="~/Content/processing.gif" /></p>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-outline-success sendSoapBtn">ОТПРАВИТЬ (test)</button>
            </div>
        </div>
        <hr />
        <div class="card soapResponse">
            <div class="card-body">
                <h5 class="card-title">Результат: Информация из СФ</h5>
                <div class="card-text pre-scrollable">
                    <table class="table table-bordered table-hover table-condensed">
                        <thead>
                            <tr>
                                <th title="Field #1">ПИН</th>
                                <th title="Field #1">Фамилия</th>
                                <th title="Field #1">Имя</th>
                                <th title="Field #1">Отчество</th>
                                <th title="Field #1">РУСФ</th>
                                <th title="Field #2">Номер ПД</th>
                                <th title="Field #3">ПИН пенсионера</th>
                                <th title="Field #4">ПИН получателя</th>
                                <th title="Field #5">Дата назначения</th>
                                <th title="Field #6">Дата завершения</th>
                                <th title="Field #7">Сумма к выплате пенсии</th>
                                <th title="Field #8">Вид пенсии</th>
                                <th title="Field #9">Категория пенсии</th>
                                <th title="Field #10">ПИН кормильца 1</th>
                                <th title="Field #11">ПИН кормильца 2</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>21411196600831</td>
                                <td>Румянцева</td>
                                <td>Людмила</td>
                                <td>Ивановна</td>
                                <td align="right">304</td>
                                <td>A340000760</td>
                                <td align="right">21411196600831</td>
                                <td align="right">21411196600831</td>
                                <td>03.01.1995</td>
                                <td> </td>
                                <td align="right">5496.00</td>
                                <td align="right">По инвалидности</td>
                                <td align="right">Инвалидность 2-й группы</td>
                                <td> </td>
                                <td> </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                @*<p class="card-text text-center">Для того чтобы протестировать запрос воспользуйтесь бесплатной программой Postman (<a target="_blank" href="https://www.getpostman.com/downloads/">скачать</a>)</p>*@

            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Свойства подключения</h5>
                <p class="card-text">Сгенерировать клиент</p>
                @if (Model.ClientDetails.Count > 0)
                {
                    <div class="alert alert-success text-right">Выполнено (clientId: <span id="clientId">@Model.ClientDetails.First().Id</span> <a href="javascript://" onclick="copyToClipboard('clientId')"><i class="fas fa-copy"></i></a>)
                        @if(User.IsInRole("Developer"))
                        {
                            @Html.ActionLink("Удалить", "DeleteClientDetails", "ServiceDescriptions", new { id = Model.ClientDetails.First().Id }, new { id = "deleteClientDetailsBtn", @class = "btn btn-danger" })
                        }
                    </div>
                    Html.RenderAction("ClientDetails", new { detailsId = Model.ClientDetails.First().Id });
                }
                else if(User.IsInRole("Developer"))
                {
                    <div class="alert alert-dark text-right">@Html.ActionLink("Выполнить", "CreateClientDetails", "ServiceDescriptions", new { serviceId = Model.Id }, new { id = "createClientDetailsBtn", @class = "btn btn-primary" })</div>
                }
            </div>
        </div>
    </div>

</div>

WEB/Views/ServiceDescriptions/_TundukServiceOperations.cshtml
@model WEB.Models.Entities.ServiceDescription
<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Шаг 1.</h5>
                <p class="card-text">Создать Tunduk-адаптер</p>
                @if (Model.ServiceDetails.Count > 0)
                {
                    <div class="alert alert-success text-right">Выполнено (@Html.DisplayNameFor(modelItem => Model.ServiceDetails.First().ServiceCode.Name)): <span id="s_serviceCode">@Html.DisplayFor(modelItem => Model.ServiceDetails.First().ServiceCode.Name)</span> <a href="javascript://" onclick="copyToClipboard('s_serviceCode')"><i class="fas fa-copy"></i></a>) @Html.ActionLink("Удалить", "DeleteServiceDetails", "ServiceDescriptions", new { id = Model.ServiceDetails.First().Id }, new { id = "deleteServiceDetailsBtn", @class = "btn btn-danger" })</div>
                    Html.RenderAction("ServiceDetails", new { detailsId = Model.ServiceDetails.First().Id });
                }
                else
                {
                    <div class="alert alert-dark text-right">@Html.ActionLink("Выполнить", "CreateServiceDetails", "ServiceDescriptions", new { serviceId = Model.Id }, new { id = "createServiceDetailsBtn", @class = "btn btn-primary" })</div>
                }
            </div>
        </div>
    </div>
</div>

WEB/Views/ServiceDescriptions/_WindowsServiceOperations.cshtml
@model WEB.Models.Entities.ServiceDescription

<div class="row">
    <div class="col-md-6">
        <table class="table">
            <tr>
                <td>@Html.ActionLink("Создание файлов и папок для сервиса", "CreateProjectFolder", "ServiceBuilder", new { name = Model.Name }, new { id = "createProjectFolderBtn", @class = "btn btn-default" })</td>
                <td class="hasProjectFolder"></td>
            </tr>
            <tr>
                <td>@Html.ActionLink("Построить сервис из проекта", "BuildProject", "ServiceBuilder", new { name = Model.Name }, new { id = "buildProjectBtn", @class = "btn btn-default" })</td>
                <td>@Html.ActionLink("Перестроить сервис", "RebuildProject", "ServiceBuilder", new { name = Model.Name }, new { id = "rebuildProjectBtn", @class = "btn btn-default" })</td>
            </tr>
            <tr>
                <td>@Html.ActionLink("Установить сервис на сервер", "InstallService", "ServiceBuilder", new { name = Model.Name }, new { id = "installServiceBtn", @class = "btn btn-default" })</td>
                <td>@Html.ActionLink("Удалить установку", "UninstallService", "ServiceBuilder", new { name = Model.Name }, new { id = "uninstallServiceBtn", @class = "btn btn-default" })</td>
            </tr>
            <tr>
                <td>@Html.ActionLink("Запустить", "StartService", "ServiceBuilder", new { name = Model.Name }, new { id = "startServiceBtn", @class = "btn btn-default" })</td>
                <td>@Html.ActionLink("Остановить", "StopService", "ServiceBuilder", new { name = Model.Name }, new { id = "stopServiceBtn", @class = "btn btn-default" })</td>
            </tr>
        </table>
    </div>
</div>