WEB/Controllers/HistoryMonitorController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEB.Models;
using WEB.Models.Entities;

namespace WEB.Controllers
{
    [Authorize]
    public class HistoryMonitorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: ReceiveMonitor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetReceiveHistory(Guid clientId)
        {
            try
            {
                var items = db.ReceiveHistoryItems.Where(x => x.ClientId == clientId).Select(x => new 
                {
                    x.EntryTime,
                    x.ErrorMessage,
                    x.Id,
                    x.InputSize,
                    x.IsSuccess,
                    x.OperationDuration,
                    x.OutputSize
                }).ToList().GroupBy(x => new DateTime(x.EntryTime.Year, x.EntryTime.Month, x.EntryTime.Day)).OrderBy(x => x.Key).Select(x => new
                {
                    Date = x.Key.ToString("yyyyMMdd"),
                    Amount = new
                    {
                        Total = x.Count(),
                        Error = x.Count(x1 => !x1.IsSuccess),
                        Success = x.Count(x1 => x1.IsSuccess)
                    }
                });
                if (items.Count() > 0)
                {
                    return Json(new { result = true, items }, JsonRequestBehavior.AllowGet);
                }
                else throw new ApplicationException("No data found!");
            }
            catch(Exception e)
            {
                return Json(new { result = false, errorMessage = e.GetBaseException().Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetTransmitHistory(int serviceDetailId)
        {
            try
            {
                var items = db.TransmitHistoryItems.Where(x => x.ServiceDetailId == serviceDetailId).Select(x => new
                {
                    x.EntryTime,
                    x.ErrorMessage,
                    x.Id,
                    x.InputSize,
                    x.IsSuccess,
                    x.OperationDuration,
                    x.OutputSize
                }).ToList().GroupBy(x => new DateTime(x.EntryTime.Year, x.EntryTime.Month, x.EntryTime.Day)).OrderBy(x => x.Key).Select(x => new
                {
                    Date = x.Key.ToString("yyyyMMdd"),
                    Amount = new
                    {
                        Total = x.Count(),
                        Error = x.Count(x1 => !x1.IsSuccess),
                        Success = x.Count(x1 => x1.IsSuccess)
                    }
                });
                if (items.Count() > 0)
                {
                    return Json(new { result = true, items }, JsonRequestBehavior.AllowGet);
                }
                else throw new ApplicationException("No data found!");
            }
            catch (Exception e)
            {
                return Json(new { result = false, errorMessage = e.GetBaseException().Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AllHistoryReceive()
        {
            var receiveQuery = db.ReceiveHistoryItems.AsQueryable().OrderByDescending(x => x.Id).Take(20);
            //if(withErrors)
            return View(receiveQuery.ToList());
        }

        public ActionResult AllHistoryTransmit()
        {
            var transmitQuery = db.TransmitHistoryItems.AsQueryable().OrderByDescending(x => x.Id).Take(20);
            //if(withErrors)
            return View(transmitQuery.ToList());
        }

    }
}

WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEB.Models;

namespace WEB.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.DashboardNav = " active";
            return View();
        }
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult GetServiceAmount()
        {
            return Json(db.ServiceDetails.Count(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetClientAmount()
        {
            return Json(db.ClientDetails.Count(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSuccessRequestsAmount()
        {
            return Json(db.ReceiveHistoryItems.Count(x => x.IsSuccess), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetErrorRequestsAmount()
        {
            return Json(db.ReceiveHistoryItems.Count(x => !x.IsSuccess), JsonRequestBehavior.AllowGet);
        }
    }
}

WEB/Controllers/ServiceDescriptionsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEB.Models;
using WEB.Models.Entities;

namespace WEB.Controllers
{
    [Authorize]
    public class ServiceDescriptionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ServiceDescriptionsController()
        {
            ViewBag.ServiceDescriptionsNav = "active";
        }
        public ActionResult Index()
        {
            return View(db.ServiceDescriptions.ToList());
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceDescription serviceDescription = db.ServiceDescriptions.Find(id);
            if (serviceDescription == null)
            {
                return HttpNotFound();
            }
            return View(serviceDescription);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,AgreementNo,ConnectionType,InteractionType,IsActive")] ServiceDescription serviceDescription)
        {
            if (db.ServiceDescriptions.Any(x => x.Name.Trim().ToUpper() == serviceDescription.Name.Trim().ToUpper()))
                ModelState.AddModelError("Name", "Сервис с таким именем уже существует в базе-данных");
            if (ModelState.IsValid)
            {
                serviceDescription.Id = Guid.NewGuid();
                serviceDescription.Name = serviceDescription.Name.Trim().ToUpper();
                db.ServiceDescriptions.Add(serviceDescription);
                db.SaveChanges();
                return RedirectToAction("Details", new { serviceDescription.Id });
            }

            return View(serviceDescription);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceDescription serviceDescription = db.ServiceDescriptions.Find(id);
            if (serviceDescription == null)
            {
                return HttpNotFound();
            }
            return View(serviceDescription);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,AgreementNo,ConnectionType,InteractionType,IsActive")] ServiceDescription serviceDescription)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceDescription).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { serviceDescription.Id });
            }
            return View(serviceDescription);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceDescription serviceDescription = db.ServiceDescriptions.Find(id);
            if (serviceDescription == null)
            {
                return HttpNotFound();
            }
            return View(serviceDescription);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ServiceDescription serviceDescription = db.ServiceDescriptions.Find(id);
            db.ServiceDescriptions.Remove(serviceDescription);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SelectTundukOrganization(Guid serviceId, int? id, string returnAction)
        {
            ViewBag.serviceId = serviceId;
            ViewBag.returnAction = returnAction;
            if (id != null)
            {
                return RedirectToAction("SelectSubsystem", new { serviceId, tundukOrganizationId = id, returnAction });
            }
            return View(db.TundukOrganizations.ToList());
        }

        public ActionResult SelectSubsystem(Guid serviceId, int tundukOrganizationId, int? id, string returnAction)
        {
            ViewBag.serviceId = serviceId;
            ViewBag.returnAction = returnAction;
            ViewBag.OrganizationName = db.TundukOrganizations.Find(tundukOrganizationId).Name;
            if (id != null)
            {
                return RedirectToAction(returnAction, new { serviceId, subsystemId = id });
            }
            var subsystems = db.Subsystems.Where(x => x.TundukOrganizationId == tundukOrganizationId).ToList();
            if(subsystems.Count == 1)
            {
                return RedirectToAction(returnAction, new { serviceId, subsystemId = subsystems[0].Id });
            }
            return View(subsystems);
        }

        public ActionResult CreateClientDetails(Guid serviceId, int? subsystemId)
        {
            if(subsystemId == null)
            {
                return RedirectToAction("SelectTundukOrganization", new { serviceId, returnAction = "CreateClientDetails" });
            }

            var serviceCodes = db.ServiceCodes.Where(x => x.SubsystemId == subsystemId).ToList();
            ViewBag.ServiceCodeId = (from sc in serviceCodes
                                     select new SelectListItem
                                     {
                                         Text = sc.Name,
                                         Value = sc.Id.ToString()
                                     });
            ViewBag.SubsystemId = subsystemId;
            var subsystem = db.Subsystems.Find(subsystemId);
            ViewBag.OrganizationName = db.TundukOrganizations.Find(subsystem.TundukOrganizationId).Name;
            ViewBag.SubsystemName = subsystem.Name;
            return View(new ClientDetail { ServiceDescriptionId = serviceId });
        }
        [HttpPost]
        public ActionResult CreateClientDetails(ClientDetail obj, int? subsystemId)
        {
            var objDb = db.ClientDetails.FirstOrDefault(x => x.ServiceCodeId == obj.ServiceCodeId);
            if (objDb != null)
            {
                ModelState.AddModelError("ServiceCodeId", "Для указанного сервиса клиент уже существует! Name: " + objDb.ServiceDescription.Name);
            }
            if (ModelState.IsValid)
            {
                obj.Id = Guid.NewGuid();
                db.ClientDetails.Add(obj);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = obj.ServiceDescriptionId });
            }

            ViewBag.ServiceCodeId = (from sc in db.ServiceCodes
                                     where sc.SubsystemId == subsystemId
                                     select new SelectListItem
                                     {
                                         Text = sc.Name,
                                         Value = sc.Id.ToString(),
                                         Selected = sc.Id == obj.ServiceCodeId
                                     }).ToList();
            ViewBag.SubsystemId = subsystemId;
            var subsystem = db.Subsystems.Find(subsystemId);
            ViewBag.OrganizationName = db.TundukOrganizations.Find(subsystem.TundukOrganizationId).Name;
            ViewBag.SubsystemName = subsystem.Name;
            return View(obj);
        }

        public ActionResult ClientDetails(Guid detailsId)
        {
            return PartialView(db.ClientDetails.Find(detailsId));
        }

        public ActionResult CreateServiceDetails(Guid serviceId, int? subsystemId)
        {
            if (subsystemId == null)
            {
                var ownerTundukMemberCode = ConfigurationManager.AppSettings["c_memberCode"];
                if (!string.IsNullOrEmpty(ownerTundukMemberCode))
                {
                    var orgFromDb = db.TundukOrganizations.FirstOrDefault(x => x.MemberCode == ownerTundukMemberCode);
                    if(orgFromDb != null)
                    {
                        return RedirectToAction("SelectTundukOrganization", new { orgFromDb.Id, serviceId, returnAction = "CreateServiceDetails" });
                    }
                }
                return RedirectToAction("SelectTundukOrganization", new { serviceId, returnAction = "CreateServiceDetails" });
            }

            var serviceCodes = db.ServiceCodes.Where(x => x.SubsystemId == subsystemId).ToList();
            ViewBag.ServiceCodeId = (from sc in serviceCodes
                                     select new SelectListItem
                                     {
                                         Text = sc.Name,
                                         Value = sc.Id.ToString()
                                     });
            ViewBag.SubsystemId = subsystemId;
            var subsystem = db.Subsystems.Find(subsystemId);
            ViewBag.OrganizationName = db.TundukOrganizations.Find(subsystem.TundukOrganizationId).Name;
            ViewBag.SubsystemName = subsystem.Name;
            var serviceDesc = db.ServiceDescriptions.Find(serviceId);
            return View(new ServiceDetail { ServiceDescriptionId = serviceId });
        }
        [HttpPost]
        public ActionResult CreateServiceDetails(ServiceDetail obj, int? subsystemId)
        {
            var objDb = db.ServiceDetails.FirstOrDefault(x => x.ServiceCodeId == obj.ServiceCodeId);
            if (objDb != null)
                ModelState.AddModelError("ServiceCodeId", "Адаптер с таким ServiceCode уже зарегистрирован! Name: " + objDb.ServiceDescription.Name);
            if (ModelState.IsValid)
            {
                db.ServiceDetails.Add(obj);
                db.SaveChanges();

WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
}



<!-- Icon Cards-->
<div class="row">
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-primary o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-cloud"></i>
                </div>
                <div class="mr-5"><span id="service-amount">0</span> сервисов</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("Index", "ServiceDescriptions")">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-info o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-list"></i>
                </div>
                <div class="mr-5"><span id="client-amount">0</span> клиентов</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("Index", "ServiceDescriptions")">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-success o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-recycle"></i>
                </div>
                <div class="mr-5"><span id="success-requests-amount">0</span> успешных запросов</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("AllHistoryReceive", "HistoryMonitor")">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-danger o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-comment-alt"></i>
                </div>
                <div class="mr-5"><span id="error-requests-amount">0</span> ошибок</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("AllHistoryTransmit", "HistoryMonitor")">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
</div>
<div class="card text-center">
    <div class="card-header">
        Министерство труда и социального развития Кыргызской Республики
    </div>
    <div class="card-body">
        <h5 class="card-title">Система обмена данными</h5>
        <p class="card-text">СОД это веб–приложение, функционирующее на основе службы веб–сервисов и использующие стандартизированный способ интеграции веб-приложений с использованием XML, SOAP, WSDL открытых стандартов, работающих на основе Интернет протоколов. СОД создает шлюз обмена данными как уникальный инструмент, позволяющий унифицировать всю работу по установлению соединений с разными источниками к единому своду правил и к единому стандарту автоматизации внешнего взаимодействия.</p>
        <div class="text-right">
            <a href="@Url.Content("~/Docs/Manual.pdf")" class="btn btn-primary" target="_blank">Открыть инструкцию по эксплуатации <i class="fas fa-external-link-alt"></i></a>
            <a href="@Url.Content("~/Docs/PublishManual.pdf")" class="btn btn-primary" target="_blank">Открыть инструкцию по установке <i class="fas fa-external-link-alt"></i></a>
        </div>
    </div>
    <div class="card-footer text-muted">
        Проект ВБ "Здравоохранение и социальная защита"
    </div>
</div>
@section breadcrumb{
<li class="breadcrumb-item active">Overview</li>
}

@section scripts{
    <script>
        $(function () {
            SetAmountOfType('@Url.Action("GetServiceAmount")', 'service-amount');
            SetAmountOfType('@Url.Action("GetClientAmount")', 'client-amount');
            SetAmountOfType('@Url.Action("GetSuccessRequestsAmount")', 'success-requests-amount');
            SetAmountOfType('@Url.Action("GetErrorRequestsAmount")', 'error-requests-amount');
        });
        function SetAmountOfType(url, elementId) {
            $.ajax(url,
                {
                    method: "GET",
                    contentType: "application/json"
                }).done(function (data) {
                    $('#' + elementId).html(data);
                }).catch(function (error) {
                    bs_alert(error);
                });
        }
    </script>
    }