WEB/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using WEB.Models;
using WEB.Models.Entities;

namespace WEB.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ReportsController()
        {
            ViewBag.ReportsNav = "active";
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult RequestByType()
        {
            var model = new RequestByTypeViewModel
            {
                SearchResult = new List<ReportItemViewModel>()
            };

            return View(model);
        }
        [HttpPost]
        public ActionResult RequestByType(RequestByTypeViewModel model)
        {
            var query = db.ServiceDescriptions.AsQueryable();

            if(model.ConnectionType != null)
            {
                query = query.Where(x => x.ConnectionType == model.ConnectionType);
            }
            if(model.InteractionType != null)
            {
                query = query.Where(x => x.InteractionType == model.InteractionType);
            }

            model.SearchResult = (from r in query
                                  select new ReportItemViewModel
                                  {
                                      Connection = r
                                  }).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult RequestByPeriod()
        {
            var model = new RequestByPeriodViewModel
            {
                SearchResult = new List<RequestByPeriodItem>()
            };

            return View(model);
        }
        [HttpPost]
        public ActionResult RequestByPeriod(RequestByPeriodViewModel model)
        {
            model.SearchResult = new List<RequestByPeriodItem>();

            var connections = db.ServiceDescriptions.Include(x => x.ClientDetails).Include(x => x.ServiceDetails).ToList();

            foreach(var c in connections)
            {
                var modelItem = new RequestByPeriodItem
                {
                    Connection = c
                };
                var receivedHistoryQuery = db.ReceiveHistoryItems.AsQueryable();
                if(c.ClientDetails.Count > 0)
                {
                    var cIds = c.ClientDetails.Select(x1 => x1.Id).ToList();
                    receivedHistoryQuery = receivedHistoryQuery.Where(x => cIds.Contains(x.ClientId ?? Guid.Empty));
                }
                else
                {
                    receivedHistoryQuery = null;
                }


                var transmittedHistoryQuery = db.TransmitHistoryItems.AsQueryable();
                if (c.ServiceDetails.Count > 0)
                {
                    var sIds = c.ServiceDetails.Select(x1 => x1.Id);
                    transmittedHistoryQuery = transmittedHistoryQuery.Where(x => sIds.Contains(x.ServiceDetailId ?? 0));
                }
                else
                {
                    transmittedHistoryQuery = null;
                }


                if (model.StartDate != null)
                {
                    receivedHistoryQuery = receivedHistoryQuery != null ? receivedHistoryQuery.Where(x => x.EntryTime >= model.StartDate) : receivedHistoryQuery;
                    transmittedHistoryQuery = transmittedHistoryQuery != null ? transmittedHistoryQuery.Where(x => x.EntryTime >= model.StartDate) : transmittedHistoryQuery;
                }
                if(model.EndDate != null)
                {
                    receivedHistoryQuery = receivedHistoryQuery != null ? receivedHistoryQuery.Where(x => x.EntryTime <= model.EndDate) : receivedHistoryQuery;
                    transmittedHistoryQuery = transmittedHistoryQuery != null ? transmittedHistoryQuery.Where(x => x.EntryTime <= model.EndDate) : transmittedHistoryQuery;
                }
                
                modelItem._ReceivedDataSize = receivedHistoryQuery != null ? receivedHistoryQuery.Sum(x => x.OutputSize) ?? 0 : 0;
                modelItem._TransmittedDataSize = transmittedHistoryQuery != null ? transmittedHistoryQuery.Sum(x => x.OutputSize) ?? 0 : 0;
                modelItem.TransmittedRows = transmittedHistoryQuery != null ? transmittedHistoryQuery.Sum(x => x.OutputRows) ?? 0 : 0;
                if (!(modelItem._ReceivedDataSize == 0 && modelItem._TransmittedDataSize == 0 && modelItem.TransmittedRows == 0))
                    model.SearchResult.Add(modelItem);
            }
            return View(model);
        }

        public ActionResult RequestByOrg()
        {
            var model = new RequestByOrgViewModel
            {
                ReceivedHistoryByOrgs = new List<RequestByOrgItem>(),
                TransmittedHistoryByOrgs = new List<RequestByOrgItem>()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult RequestByOrg(RequestByOrgViewModel model)
        {
            model.ReceivedHistoryByOrgs = new List<RequestByOrgItem>();
            model.TransmittedHistoryByOrgs = new List<RequestByOrgItem>();

            var receiveHistoryQuery = db.ReceiveHistoryItems.AsQueryable();
            var transmitHistoryQuery = db.TransmitHistoryItems.AsQueryable();
            if (model.StartDate != null)
            {
                receiveHistoryQuery = receiveHistoryQuery.Where(x => x.EntryTime >= model.StartDate);
                transmitHistoryQuery = transmitHistoryQuery.Where(x => x.EntryTime >= model.StartDate);
            }
            if (model.EndDate != null)
            {
                receiveHistoryQuery = receiveHistoryQuery.Where(x => x.EntryTime <= model.EndDate);
                transmitHistoryQuery = transmitHistoryQuery.Where(x => x.EntryTime <= model.EndDate);
            }

            var receiveOrgs = receiveHistoryQuery.Select(x => x.Client.ServiceCode.Subsystem.TundukOrganization.MemberCode).Distinct().ToList();
            foreach(var orgCode in receiveOrgs)
            {
                //Организация, откуда было поступление данных в КИССП
                var org = db.TundukOrganizations.FirstOrDefault(x => x.MemberCode == orgCode);
                if(org == null)
                {
                    org = new TundukOrganization { MemberCode = orgCode, Name = "НЕИЗВЕСТНО" };
                }
                //все клиенты к данной организации
                var orgReceiveHistoryQuery = receiveHistoryQuery.Where(x => x.Client.ServiceCode.Subsystem.TundukOrganization.MemberCode == orgCode);
                foreach(var conName in orgReceiveHistoryQuery.Select(x => x.Client.ServiceDescription.Name).Distinct().ToList())
                {
                    var connRequests = orgReceiveHistoryQuery.Where(x => x.Client.ServiceDescription.Name == conName);
                    foreach (var consumer in connRequests.GroupBy(x => x.OrgName ?? "-"))
                    {
                        var item = new RequestByOrgItem
                        {
                            ConnectionName = conName,
                            Organization = org,
                            OrgName = consumer.Key,
                            SentRequests = consumer.Count(),
                            Region = consumer.First().Region
                        };
                        model.ReceivedHistoryByOrgs.Add(item);
                    }
                }
            }

            var transmitOrgs = transmitHistoryQuery.Select(x => x.c_memberCode).Distinct().ToList();
            foreach (var orgCode in transmitOrgs)
            {
                //Организация, куда были переданы данные из КИССП
                var org = db.TundukOrganizations.FirstOrDefault(x => x.MemberCode == orgCode);
                if (org == null)
                {
                    org = new TundukOrganization { MemberCode = orgCode, Name = "НЕИЗВЕСТНО" };
                }
                //все трансферы в данную организацию
                var orgTransmitHistoryQuery = transmitHistoryQuery.Where(x => x.c_memberCode == orgCode);
                foreach (var conName in orgTransmitHistoryQuery.ToList().Select(x => (x.ServiceDetail ?? new ServiceDetail { ServiceCode = new ServiceCode { Name = x.ErrorMessage } }).ServiceCode.Name).Distinct())
                {
                    var item = new RequestByOrgItem
                    {
                        ConnectionName = conName,
                        Organization = org,
                        ReceivedRequests = orgTransmitHistoryQuery.ToList().Where(x => (x.ServiceDetail != null && x.ServiceDetail.ServiceCode.Name == conName) || (x.ErrorMessage == conName)).Count()
                    };
                    model.TransmittedHistoryByOrgs.Add(item);
                }
            }

            ViewBag.DateFromStr = model.StartDate?.ToString("yyyy-MM-dd");
            ViewBag.DateToStr = model.EndDate?.ToString("yyyy-MM-dd");
            model.StartDate = null;
            model.EndDate = null;
            return View(model);
        }
    }
}

WEB/Controllers/TundukOrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEB.Models;
using WEB.Models.Entities;

namespace WEB.Controllers
{
    [Authorize]
    public class TundukOrganizationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(db.TundukOrganizations.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TundukOrganization tundukOrganization = db.TundukOrganizations.Find(id);
            if (tundukOrganization == null)
            {
                return HttpNotFound();
            }
            return View(tundukOrganization);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,MemberCode")] TundukOrganization tundukOrganization)
        {
            if (ModelState.IsValid)
            {
                db.TundukOrganizations.Add(tundukOrganization);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tundukOrganization);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TundukOrganization tundukOrganization = db.TundukOrganizations.Find(id);
            if (tundukOrganization == null)
            {
                return HttpNotFound();
            }
            return View(tundukOrganization);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,MemberCode")] TundukOrganization tundukOrganization)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tundukOrganization).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tundukOrganization);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TundukOrganization tundukOrganization = db.TundukOrganizations.Find(id);
            if (tundukOrganization == null)
            {
                return HttpNotFound();
            }
            return View(tundukOrganization);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TundukOrganization tundukOrganization = db.TundukOrganizations.Find(id);
            db.TundukOrganizations.Remove(tundukOrganization);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CreateSubsystem(int tundukOrganizationId)
        {
            var model = new Subsystem
            {
                TundukOrganizationId = tundukOrganizationId,
                TundukOrganization = db.TundukOrganizations.Find(tundukOrganizationId)
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult CreateSubsystem(Subsystem model)
        {
            if(db.Subsystems.Any(x => x.Name == model.Name && x.TundukOrganizationId == model.TundukOrganizationId))
            {
                ModelState.AddModelError("Name", "Already exist");
            }
            if (ModelState.IsValid)
            {
                db.Subsystems.Add(model);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = model.TundukOrganizationId });
            }
            model.TundukOrganization = db.TundukOrganizations.Find(model.TundukOrganizationId);
            return View(model);
        }

        public ActionResult CreateServiceCode(int subsystemId)
        {
            var model = new ServiceCode
            {
                SubsystemId = subsystemId,
                Subsystem = db.Subsystems.Find(subsystemId)
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult CreateServiceCode(ServiceCode model)
        {
            if (db.ServiceCodes.Any(x => x.Name == model.Name && x.Version == model.Version && x.SubsystemId == model.SubsystemId))
            {
                ModelState.AddModelError("Name", "Already exist");
            }
            var subsystem = db.Subsystems.Find(model.SubsystemId);
            if (ModelState.IsValid)
            {
                db.ServiceCodes.Add(model);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = subsystem.TundukOrganizationId });
            }
            model.Subsystem = subsystem;
            return View(model);
        }

        public ActionResult DeleteServiceCode(int id)
        {
            var obj = db.ServiceCodes.Find(id);
            var orgId = obj.Subsystem.TundukOrganizationId;
            if (obj != null)
            {
                db.ServiceCodes.Remove(obj);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = orgId });
            }
            return HttpNotFound();
        }
        public ActionResult DeleteSubsystem(int id)
        {
            var obj = db.Subsystems.Find(id);
            var orgId = obj.TundukOrganizationId;
            if (obj != null)
            {
                db.Subsystems.Remove(obj);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = orgId });
            }
            return HttpNotFound();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WEB/Views/Shared/_Layout-dark.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - Конструктор веб-сервисов</title>
    @Styles.Render(System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css", true))
    @Styles.Render("~/bs-datepicker/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    @RenderSection("styles", required: false)
    <!-- Page level plugin CSS-->
    <link href="~/dark_theme/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/dark_theme/css/sb-admin.css" rel="stylesheet">
    <style>
        #bs-alert {
            z-index: 2000;
            position: fixed;
            margin: 0px auto;
            display: none;
            left: 35%;
            right: 35%;
        }

        @@media (min-width: 768px) {
            .navbar-brand.abs {
                position: absolute;
                width: 100%;
                left: 0;
                text-align: center;
            }
        }
        }
    </style>
</head>
<body id="page-top" @*style="padding: 0px !important;"*@>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <a class="navbar-brand mr-1" href="@Url.Action("Index", "Home")">СОД</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search -->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">
            @*<li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>
                    <span class="badge badge-danger">9+</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <span class="badge badge-danger">7</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>*@
            @Html.Partial("_LoginPartialDark")
        </ul>
    </nav>
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item @ViewBag.DashboardNav">
                <a class="nav-link" href="@Url.Action("Index", "Home")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item @ViewBag.ServiceDescriptionsNav">
                <a class="nav-link" href="@Url.Action("Index", "ServiceDescriptions")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Список сервисов</span>
                </a>
            </li>
            <li class="nav-item @ViewBag.ReportsNav">
                <a class="nav-link" href="@Url.Action("RequestByOrg", "Reports")">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Отчеты-статистика</span>
                </a>
            </li>
            @if (User.IsInRole("Developer"))
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-fw fa-folder"></i>
                        <span>Справочники</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                        <h6 class="dropdown-header">Тундук:</h6>
                        <a class="dropdown-item" href="@Url.Action("Index", "TundukOrganizations")">Организации</a>
                    </div>
                    @*<div class="dropdown-menu" aria-labelledby="pagesDropdown">
                    <h6 class="dropdown-header">Login Screens:</h6>
                    <a class="dropdown-item" href="@Url.Content("~/dark_theme/login.html")">Login</a>
                    <a class="dropdown-item" href="@Url.Content("~/dark_theme/register.html")">Register</a>
                    <a class="dropdown-item" href="@Url.Content("~/dark_theme/forgot-password.html")">Forgot Password</a>
                    <div class="dropdown-divider"></div>
                    <h6 class="dropdown-header">Other Pages:</h6>
                    <a class="dropdown-item" href="@Url.Content("~/dark_theme/404.html")">404 Page</a>
                    <a class="dropdown-item" href="@Url.Content("~/dark_theme/blank.html")">Blank Page</a>
                </div>*@
                </li>
            }
        </ul>
        <div id="content-wrapper">
            <div class="container-fluid">
                <div id="bs-alert" class="alert">
                    <strong id="bs-alert-type"></strong> <span id="bs-alert-message"></span>
                </div>
                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index", "Home")">Dashboard</a>
                    </li>
                    @RenderSection("breadcrumb", false)
                </ol>
                @RenderBody()
            </div>
            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>&copy; @DateTime.Now.Year - Разработчик Intersoft</span>
                    </div>
                </div>
            </footer>
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    @*<a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>*@
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-primary">Logout</a>
                    }
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    <script src="http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    @Scripts.Render(System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/bootstrap", true))
    @Scripts.Render("~/bs-datepicker/js")
    <!-- Custom scripts for all pages-->
    <script src="~/dark_theme/js/sb-admin.min.js"></script>
    @RenderSection("scripts", required: false)
    <script>
        function copyToClipboard(elementId) {

            /* Get the text field */
            var copyText = document.getElementById(elementId);

            var secretInfo = copyText.innerText;
            var $body = document.getElementsByTagName('body')[0];
            var $tempInput = document.createElement('INPUT');
            $body.appendChild($tempInput);
            $tempInput.setAttribute('value', secretInfo)
            $tempInput.select();
            document.execCommand('copy');
            $body.removeChild($tempInput);
            /* Alert the copied text */
            bs_alert("Copied the text: " + copyText.innerText, { type: 'info', durationMs: 3000 });
        }
        function bs_alert(message, { type, durationMs } = { type: 'danger', durationMs: 10000 }) {
            $('#bs-alert-message').html(message);
            $('#bs-alert-type').html('Alert:');
            $('#bs-alert').fadeIn(300).attr('class', 'alert').addClass('alert-' + type);
            setTimeout(function () {
                $('#bs-alert').fadeOut(300);
            }, durationMs);
        }
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $(".bs_datepicker").datepicker({
                format: "yyyy-mm-dd",
                language: "ru",
                todayHighlight: true,
                clearBtn: true
            });
        });
    </script>
</body>
</html>

WEB/Views/Shared/_Layout-old.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Web services", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Intersoft Ltd.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WEB/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - Конструктор веб-сервисов</title>
    @Styles.Render(System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css", true))
    @Styles.Render("~/bs-datepicker/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    @RenderSection("styles", required: false)
    <!-- Page level plugin CSS-->
    <link href="~/dark_theme/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/dark_theme/css/sb-admin.css" rel="stylesheet">
</head>
<body class="bg-dark">
    <div class="container">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    <script src="http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    @Scripts.Render(System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/bootstrap", true))
</body>
</html>

WEB/Views/Shared/_LoginPartialDark.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i> @User.Identity.GetUserName()
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="@Url.Action("Index", "Manage")">Управление</a>
            <a class="dropdown-item" href="#">Activity Log</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
    </li>
}
else
{
    <li class="nav-item">@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "nav-link" })</li>
    <li class="nav-item">@Html.ActionLink("Login", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })</li>
}